name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/king-of-the-hill-frontend:latest
        build-args: |
          VITE_NETWORK_NAME=${{ secrets.VITE_NETWORK_NAME }}
          VITE_CHAIN_ID=${{ secrets.VITE_CHAIN_ID }}
          VITE_RPC_URL=${{ secrets.VITE_RPC_URL }}
          VITE_CONTRACT_ADDRESS=${{ secrets.VITE_CONTRACT_ADDRESS }}
    
    - name: Deploy to VDS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USERNAME }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          # Stop old container
          docker stop king-of-the-hill-frontend || true
          docker rm king-of-the-hill-frontend || true
          
          # Remove old image
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/king-of-the-hill-frontend:latest || true
          
          # Login to DockerHub
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          
          # Run new container
          docker run -d --name king-of-the-hill-frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/king-of-the-hill-frontend:latest
    